events {
  worker_connections 4096;
}

http {
  upstream backend_cluster {
    least_conn;

    server backend-backend-1:4000;
    server backend-backend-2:4000;
    server backend-backend-3:4000;

    keepalive 100;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://backend_cluster;

      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host $host;

      proxy_connect_timeout 10s;
      proxy_read_timeout 30s;
      proxy_send_timeout 30s;
    }
  }
}